src/views/Finances/components/LegendItemChart/LegendItemWaterfall.tsx, src/views/Finances/components/LineYearBorderBottomChart/LineYearBorderBottomChart.tsx, src/views/Finances/components/ReservesWaterfallFilters/BudgetItem.tsx, src/views/Finances/components/ReservesWaterfallFilters/CustomAllCategories.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.stories.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts, src/views/Finances/components/WaterfallChart/WaterfallChart.tsx, src/views/Finances/utils/utils.ts
=> [🎟️ Ticket-590] Add style for small resolution in both axis

src/views/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx, src/views/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx, src/views/Finances/components/SectionPages/OverviewSection/OverviewSection.tsx, src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/DesktopChart/DesktopChart.tsx
Fix pie legend issues and navigation cards
=> [Reskin-485] Fix card width

src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/FilterTabs/FilterTabs.tsx
Add a "smoke" in the tabs when there are more tabs to the left/right
=> [Reskin-485] Add tabs gradient

src/views/Finances/FinancesView.tsx
Update the sections position in the finances page
=> [Reskin-491] Change finance's sections order

src/components/FiltersBundle/defaults/SelectAsList.tsx, src/components/FiltersBundle/types.ts, src/views/Finances/components/ReservesWaterfallFilters/BudgetItem.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
=> 🎟️ [Ticket-490]: Reskin waterfall filters

src/views/Finances/components/FinancesTable/CellTable.tsx, src/views/Finances/components/FinancesTable/FinancesTable.tsx, src/views/Finances/components/HeaderTable/HeaderAnnually/CellAnnually.tsx, src/views/Finances/components/HeaderTable/HeaderMonthly/CellMonthly.tsx, src/views/Finances/components/HeaderTable/HeaderQuarterly/CellQuarterly.tsx, src/views/Finances/components/HeaderTable/HeaderSemiAnnual/CellSemiAnnual.tsx, src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTable.tsx
Updated breakdown table body styles
=> [Reskin-491] Breakdown table body

src/views/CoreUnitAbout/components/Button/BigButton/BigButton.tsx, src/views/Finances/components/SectionPages/ExpenseReports/ExpenseReports.tsx
https://trello.com/c/oWvg96oH/492-reskin-finances-budget-statements
Reskin Finances: Budget Statements
=> feat: Reskin Finances: Budget Statements

src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/BreakdownTableBodySkeleton.tsx, src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/HeaderRowSkeleton.tsx, src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/HeaderRowSkeletonTitle.tsx, src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableBodySkeleton/RowSkeleton.tsx, src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/BreakdownTableSkeleton.tsx, src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/HeaderBreakdownTableSkeleton.tsx, src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/HeaderTitleSkeleton.tsx, src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTableSkeleton/ItemHeaderSkeleton.tsx
Applied the new styles to the breakdown table loading state
=> [Reskin-491] Breakdown table loading state

src/views/Finances/FinancesView.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
https://trello.com/c/6H8x1mXD/486-reskin-finances-breakdown-chart
=> [Reskin-486] Add Filters for mobile

src/components/FiltersBundle/FilterTablet.tsx, src/components/FiltersBundle/FiltersBundle.tsx, src/components/FiltersBundle/FiltersList.tsx, src/components/FiltersBundle/defaults/SelectAsList.tsx, src/components/FiltersBundle/types.ts, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
=> [Reskin-490]  Add the filter for desk resolution

src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTable.stories.tsx, src/views/Finances/components/SectionPages/BreakdownTable/storiesDataMock.ts
Created stories for loading state and with data
=> [Reskin-491] Breakdown table stories

src/views/Finances/FinancesView.tsx, src/views/Finances/components/BreakdownChartSection/BreakdownChartSection.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx, src/views/Finances/components/WaterfallChart/WaterfallChart.tsx
[X] Add the responsive for mobile  resolution first iteration 
[X] Add the correct space for the breakdown chart
=> [Reskin-490 ]🚀 Add responsive for mobile resolution firts iteration

src/views/Finances/components/WaterfallChart/WaterfallChart.tsx
https://trello.com/c/6H8x1mXD/486-reskin-finances-breakdown-chart
=> 🚀 [Reskin-486] Improve the responsive desk and mobile

src/views/Finances/components/BreakdownChartSection/BreakdownChart/LegendBreakDownChart/LegendBreakDownChart.tsx, src/views/Finances/components/BreakdownChartSection/BreakdownChart/LegendBreakDownChart/LegendItemBreakDownChart.tsx, src/views/Finances/components/BreakdownChartSection/useBreakdownChart.ts
https://trello.com/c/6H8x1mXD/486-reskin-finances-breakdown-chart
=> 🚀[Reskin-486] Show the correct data in the legend of breakdown chart

src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.stories.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/utils.ts, src/views/Finances/components/WaterfallChart/WaterfallChart.tsx
=>  [Reski-490] Add the story book for Desk

src/stories/containers/ActorProjects/components/PageSubheader/PageSubheader.tsx
https://trello.com/c/VIIpc7Ew/570-tpd-21-powerhouse-project-details-page
=> [Reskin-570] Add correct color and size for the title in project

src/views/ActorProjects/ActorProjectsContainer.tsx, src/views/ActorProjects/components/BudgetTypeBadge/BudgetTypeBadge.tsx, src/views/ActorProjects/components/ProjectCard/ProjectCard.tsx, src/views/ActorProjects/components/ProjectList/ProjectList.tsx
https://trello.com/c/VIIpc7Ew/570-tpd-21-powerhouse-project-details-page
[X] Add the container for the image and data
[X] Add the the image in all dimensions
[X] Add the style for the container of the data small/desk resolutions
=> [Reskin-570]  Project details page add container

src/views/ActorProjects/components/ProjectCard/ProjectCard.tsx, src/views/ActorProjects/components/ProjectParticipants/ProjectOwner.tsx, src/views/ActorProjects/components/ProjectParticipants/ProjectParticipants.tsx, src/views/ActorProjects/components/ProjectParticipants/ProjectSupportTooltip.tsx, src/views/ActorProjects/components/ProjectParticipants/ProjectSupported.tsx, src/views/ActorProjects/components/SupportedTeamsAvatarGroup/SupportedTeamsAvatarGroup.tsx
https://trello.com/c/VIIpc7Ew/570-tpd-21-powerhouse-project-details-page
[X] Add style for Progress card small/desk
[X] Add Contributors card small/desk (hover title)
=> [Reskin-570] Add the component progress and contribuitors

src/views/ActorProjects/ActorProjectsContainer.tsx, src/views/ActorProjects/components/ProjectCard/ProjectCard.stories.tsx, src/views/ActorProjects/components/ProjectCard/ProjectCard.tsx, src/views/ActorProjects/components/ProjectParticipants/ProjectParticipants.tsx
https://trello.com/c/VIIpc7Ew/570-tpd-21-powerhouse-project-details-page
=> [Reskin-570] Add the style for project

src/views/Finances/components/BreakdownChartSection/useBreakdownChart.ts
https://trello.com/c/wovUqrf1/586-deeplink-creation
Save the filter state of the breakdown chart in the URL, and restore the filter state on page load too
=> [Reskin-586] Keep filter state in the url in the breakdown chart

.github/workflows/staging-deploy.yaml
No ticket
Update the API secret variable name for staging deploy
=> Update staging api url

src/views/ActorProjects/components/ProjectEmptyLoadingState/KeyResultCard.tsx, src/views/ActorProjects/components/ProjectEmptyLoadingState/LoadingEmptyCard.tsx, src/views/ActorProjects/components/ProjectEmptyLoadingState/RectangleSkeleton.tsx, src/views/ActorProjects/components/ProjectList/ProjectList.tsx
https://trello.com/c/aowQHhbg/582-tpd-create-the-empty-state-component-for-team-projects
=> [Reskin:582] Add folder for the components to sync with other devs

src/components/CSSMediaQuery/CSSMediaQuery.tsx, src/views/ActorProjects/components/DeliverableCard/DeliverableCard.tsx, src/views/ActorProjects/components/DeliverablePercentageBar/DeliverablePercentageBar.tsx, src/views/ActorProjects/components/DeliverableStatusChip/DeliverableStatusChip.tsx, src/views/ActorProjects/components/KeyResults/KeyResults.tsx, src/views/ActorProjects/components/KeyResults/MaybeScrollableList.tsx, src/views/ActorProjects/components/MilestoneLink/MilestoneLink.tsx, src/views/ActorProjects/components/ProjectLink/ProjectLink.tsx, src/views/RoadmapMilestones/RoadmapMilestonesView.tsx, src/views/RoadmapMilestones/components/MilestoneDetailsCard/Contributors.tsx, src/views/RoadmapMilestones/components/MilestoneDetailsCard/Coordinators.tsx, src/views/RoadmapMilestones/components/MilestoneDetailsCard/DeliverablesSection.tsx, src/views/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneDetailsCard.tsx, src/views/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneProgress.tsx, src/views/RoadmapMilestones/components/MilestoneDetailsCard/PercentageProgressBar.tsx, src/views/RoadmapMilestones/components/MilestoneDetailsCard/StatsData.tsx, src/views/RoadmapMilestones/components/sections/DetailsSection/DetailsSection.tsx, src/views/RoadmapMilestones/useRoadmapMilestonesView.ts, styles/theme/shadows.ts
https://trello.com/c/7jLph6zE/535-reskin-single-roadmap-page
Apply the reskin design to the milestone details card section
=> [Reskin-535] Milestone details card

src/views/ActorProjects/components/ProjectEmptyLoadingState/KeyResultCard.tsx, src/views/ActorProjects/components/ProjectEmptyLoadingState/SecondSectionCardSkeleton.tsx, src/views/ActorProjects/components/ProjectEmptyLoadingState/SkeletonEmptyCard.tsx, src/views/ActorProjects/components/ProjectEmptyLoadingState/keyResulItem.tsx, src/views/ActorProjects/components/ProjectList/ProjectList.tsx
https://trello.com/c/aowQHhbg/582-tpd-create-the-empty-state-component-for-team-projects
=> [Reskin-582] Add card to empty state component

src/views/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
https://trello.com/c/oWvg96oH/492-reskin-finances-budget-statements
=> [Reskin-492] Fix the header column and the values should be aligned

src/core/context/MainWrapper.tsx, src/stories/components/404/NotFound404.tsx, src/stories/components/CheckBox/CheckBox.tsx, src/stories/components/CookiesPolicyBanner/CookiesPolicyBanner.tsx, src/stories/containers/CookiesPolicy/CookiesPolicyContainer.tsx
https://trello.com/c/1ElcR7nr/591-reskin-cookies
RESKIN Cookies
=> feat & fix: RESKIN Cookies

src/views/Home/components/FinancesSection/Notice.tsx
https://trello.com/c/KTIJ7vx8/594-update-finances-copy-on-the-homepage
Update Finances copy on the Homepage
=> fix: Update Finances copy on the Homepage

src/components/ProgressWithStatus/ProgressWithStatus.tsx, src/views/Home/components/MilestoneCard/useMilestoneCard.tsx, src/views/RoadmapMilestones/components/MilestoneCard/MilestoneCard.tsx, src/views/RoadmapMilestones/staticData.ts
https://trello.com/c/SgQTFYHs/597-milestone-status-copy-and-representation
Update Milestone Status copy and representation
=> fix: Milestone Status copy and representation

.github/workflows/dev-deploy.yaml, .github/workflows/production-deploy.yaml, .github/workflows/staging-deploy.yaml, app/robots.ts, pages/_app.tsx, public/index.html, public/robots.txt, src/config/routes.ts, src/stories/containers/Auth/Login/LoginContainer.tsx, src/stories/containers/CUActivity/CUActivityFeedContainer.tsx, src/stories/containers/CookiesPolicy/CookiesPolicyContainer.tsx, src/stories/containers/GlobalActivity/GlobalActivityFeedContainer.tsx, src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx, src/views/BudgetStatement/BudgetStatementView.tsx, src/views/BudgetStatement/useBudgetStatementView.ts, src/views/CoreUnitsIndex/CoreUnitsIndexView.tsx, src/views/Finances/FinancesView.tsx, src/views/Finances/useFinancesView.tsx, src/views/RecognizedDelegatesBudgetStatement/RecognizedDelegatesBudgetStatementView.tsx, src/views/RoadmapMilestones/RoadmapMilestonesView.tsx
https://trello.com/c/jvIaPTCM/578-seo-updates-for-fusion-release
Update SEO element to migrate to new brand sky
=> [Rebrand-578] Sky seo

src/components/FiltersBundle/defaults/CumulativeFilter/CumulativeFilter.tsx, src/views/Finances/components/BreakdownChartSection/useBreakdownChart.ts, src/views/Finances/components/SectionPages/ExpenseReports/ExpenseReportsFilters.tsx, src/views/Finances/utils/utils.ts
https://trello.com/c/SCfXrMha/593-show-selected-filters
=> [FIX-593]Fix issues in the filter

src/components/FiltersBundle/defaults/CumulativeFilter/CumulativeFilter.tsx, src/views/Finances/components/ExpenseMetrics/useExpenseMetrics.tsx
https://trello.com/c/SCfXrMha/593-show-selected-filters
=> [QA-593] Add small text for select cumulative in line chart

src/components/FiltersBundle/FiltersList.tsx, src/components/FiltersBundle/defaults/CumulativeFilter/CumulativeAsList.tsx, src/components/FiltersBundle/defaults/CumulativeFilter/CumulativeFilter.tsx, src/components/FiltersBundle/defaults/FilterAsListBase.tsx, src/components/FiltersBundle/types.ts, src/views/Finances/components/ExpenseMetrics/ExpenseMetrics.tsx, src/views/Finances/components/ExpenseMetrics/useExpenseMetrics.tsx
https://trello.com/c/SCfXrMha/593-show-selected-filters
=> [FIX-593] Add list filter in mobile

src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx
=> fix: View budget button color

src/components/FiltersBundle/defaults/CumulativeFilter/CumulativeFilter.tsx, src/components/FiltersBundle/defaults/CumulativeFilter/CumulativeSelectItem.tsx
https://trello.com/c/SCfXrMha/593-show-selected-filters
=> Add the styles in the metric line chart

Dockerfile
Add args and remove copy .env on Dockerfile
=> Fix Dockerfile args

.github/workflows/dev-deploy.yaml, .github/workflows/production-deploy.yaml, .github/workflows/staging-deploy.yaml
https://trello.com/c/wGQQR53Y/589-fusion-domain-deployment
=> Auto deploy staging and production envs

pages/contributors/index.tsx, src/views/Contributors/ContributorsView.tsx
[X] Add the both new container
[X] Add the tabs for the container items
https://trello.com/c/jdZ4dG8o/526-cgp-12-contributors-list-section
=> [Feature-526] Add the styles for contributos page

pages/contributors/index.tsx, src/views/Contributors/ContributorsView.tsx, src/views/Home/components/Contributors/ContributorsItem.tsx, src/views/Home/components/Contributors/ContributorsSection.tsx, src/views/Home/components/Contributors/Profile.tsx, src/views/Home/components/Contributors/useContributorsSection.tsx
https://trello.com/c/jdZ4dG8o/526-cgp-12-contributors-list-section-new-section
[X] Should add the All tab content.
=> [Feat-526] Feat contributors list section add item

src/views/Home/components/Contributors/ContributorsItem.stories.tsx, src/views/Home/components/Contributors/ContributorsItem.tsx, src/views/Home/components/Contributors/Profile.tsx, src/views/Home/components/Contributors/ProfileUpdated.tsx, src/views/Home/components/Contributors/useContributorsSection.tsx
https://trello.com/c/jdZ4dG8o/526-cgp-12-contributors-list-section-new-section
=> [Feat-526] Add the ecosystem actor Item in the tab

src/components/CookiesPolicyBanner/CookiesPolicyBanner.stories.tsx, src/views/CookiesPolicy/CookiesPolicyView.stories.tsx, src/views/CookiesPolicy/CookiesPolicyView.tsx, src/views/Disclaimer/DisclaimerView.tsx
https://trello.com/c/sYq1ojNY/607-reskin-cookies
RESKIN Cookies
=> feat: RESKIN Cookies

src/views/Contributors/ContributorsView.tsx, src/views/Contributors/components/Sections/ContributorsListSections.tsx, src/views/Home/components/Contributors/ContributorsItem.tsx
What solved
https://trello.com/c/jdZ4dG8o/526-cgp-12-contributors-list-section-new-section
=> [Feat-526] Add Core Unit tabs items

src/components/CustomSelect/CustomSelect.tsx, src/components/ExternalLinkButton/ExternalLinkButton.tsx, src/components/FiltersBundle/FilterDesktop.tsx, src/components/InternalLinkButton/InternalLinkButton.tsx, src/components/TopBarNavigation/LinkNavBar.tsx, src/components/TopBarNavigation/TopBarNavigation.tsx, src/components/TopBarNavigation/useTopBarNavigation.tsx, src/views/Home/components/Contributors/ContributorsDescription.tsx
Fix console errors on homepage
=> Fix console issues on homepage

src/views/Home/api/finances.ts
https://trello.com/c/EBEL97Zi/618-negative-value-in-support-scope
=> Fix Operational Reserves negative numbers

src/views/Endgame/components/IntroductoryHeadline/IntroductoryHeadline.tsx
https://trello.com/c/a1NTEuF2/620-dashboard-copy-changes
Dashboard copy changes
=> [FIX-620] Dashboard copy changes

src/views/Home/components/FinancesBarChart/FinancesBarChart.tsx, src/views/Home/components/FinancesBarChart/useFinancesBarChart.tsx, src/views/Home/components/FinancesBarChartCard/FinancesBarChartCard.tsx
https://trello.com/c/hwU01hNC/622-apply-changes-to-the-sky-ecosystem-finances-section
Apply changes to the Sky Ecosystem Finances section
=> [FIX-622] Apply changes to the Sky Ecosystem Finances section

src/components/CookiesPolicyBanner/CookiesPolicyBanner.tsx, src/core/context/MainWrapper.tsx
https://trello.com/c/sYq1ojNY/607-reskin-cookies
Improve cookies banner in mobile
=> [FIX-607] RESKIN Cookies - Improve cookies banner in mobile

src/views/Home/components/GovernanceSection/Proposal/Proposal.tsx
https://trello.com/c/Rs7Ri9j0/623-fix-governance-section
=> [Reskin-623] Fix proposal description width

.github/workflows/production-deploy.yaml
https://trello.com/c/C5LDWdjL/624-add-environment-variables-in-expense-makerdao
Updated the base URL for production actions to handle form secrets
=> Fix production base url in github actions

src/stories/components/Breadcrumbs/Breadcrumbs.tsx, src/stories/containers/FinancesOverview/components/CostBreakdownTable/ExpenseCategoryGroup.tsx, src/views/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx, src/views/Finances/components/FinancesTable/FinancesTable.tsx, src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/DesktopChart/DesktopChart.tsx
=> [Fix-614]   Fix error tag link are nested

src/views/Home/api/finances.ts
https://trello.com/c/EBEL97Zi/618-negative-value-in-support-scope
Removed the absolute values from the Operational reserves calculation formula
=> Fix operation reserves formula

src/core/hooks/useRestorationFromUrlState.ts
https://trello.com/c/aHMHVwYk/625-fix-deeplink-for-breakdown-chart
Fix deeplink for Breakdown Chart
=> [FIX-625] Fix deeplink for Breakdown Chart

src/views/Home/api/finances.ts
https://trello.com/c/EBEL97Zi/618-negative-value-in-support-scope
The operational reserves data is now calculated using ProtocolNetOutflow  - PaymentsOnChain
=> Update Operational Reserves calculation to use PaymentsOnChain

src/components/CheckBox/CheckBox.tsx, src/components/CircleAvatar/CircleAvatar.tsx, src/components/Container/PageContainer.tsx, src/components/CustomSelect/CustomSelect.tsx, src/components/Tabs/Tab.tsx
=> [Fix-614] Add the shouldForwardProp

src/components/CheckBox/CheckBox.tsx, src/components/CircleAvatar/CircleAvatar.tsx, src/components/Container/PageContainer.tsx, src/components/CustomSelect/CustomSelect.tsx, src/components/Tabs/Tab.tsx, src/views/Finances/components/ExpenseMetrics/useExpenseMetrics.tsx
https://trello.com/c/bxst5JoZ/629-fix-cumulative-filter-in-mobile-resolution
=> [Fix-629] Filter line chart accumulative

src/views/Home/components/ButtonLinkAvatar/ButtonLinkAvatar.stories.tsx, src/views/Home/components/ButtonLinkAvatar/ButtonLinkAvatar.tsx
=> [Feat-610] Add the link avatar component

src/components/AccountsSnapshot/components/CUReserves/CUReserves.tsx, src/components/AccountsSnapshot/components/Cards/FundChangeCard.tsx, src/components/AccountsSnapshot/components/Cards/ReserveCard.tsx, src/components/AccountsSnapshot/components/SectionHeader/SectionHeader.tsx, src/components/BudgetStatement/BudgetStatementPager/BudgetStatementPager.tsx, src/components/TeamHeader/TeamHeader.tsx
https://trello.com/c/3qMKYLNp/494-bss-11-budget-statement-pages-for-keepers
=> [Reskin-494] Reskin BS for keepers, SPFs and aligned delegates

src/components/AccountsSnapshot/components/CUReserves/CUReserves.stories.tsx, src/components/AdvancedInnerTable/BasicModal/CategoryContainerModal.stories.tsx, src/components/AdvancedInnerTable/BasicModal/CategoryContainerModal.tsx, src/components/AdvancedInnerTable/BasicModal/CategoryModalComponent.tsx, src/components/BudgetStatement/BudgetStatementTransferRequest/components/ModalSheet/ModalSheetValueContent.stories.tsx, src/views/CoreUnitBudgetStatement/components/ExpenseReportStatus/ExpenseReportStatus.stories.tsx, src/views/CoreUnitsIndex/components/ToolTips/SummaryToolTip.stories.tsx
https://trello.com/c/ny8qhblu/314-storybook-figma-integration-adjustments
Organize some stories in the right place and fixed some issues that make false changes detected by chromatic
=> refactor(storybook): story location & issues

src/components/FiltersBundle/useFiltersBundle.ts, src/components/SortsBundle/useSortsBundle.ts
https://trello.com/c/wSr0Lcl6/617-fix-scrolling-behavior-in-mobile-devices
Fix scrolling behavior in mobile devices
=> [FIX-617] Fix scrolling behavior in mobile devices

src/views/Contributors/ContributorsView.stories.tsx, src/views/Contributors/ContributorsView.tsx, src/views/Contributors/components/Sections/ContributorsCategorySection.tsx, src/views/Contributors/staticData.ts, src/views/Home/components/ButtonLinkAvatar/ButtonLinkAvatar.tsx, src/views/Home/components/Contributors/useContributorsSection.tsx
=> Add the tabs for the category

pages/_app.tsx, src/components/InternalLinkButton/InternalLinkButton.tsx, src/views/ActorProjects/components/ProjectLink/ProjectLink.tsx, src/views/Endgame/components/NavigationTabs/NavigationTabs.tsx, src/views/Endgame/useEndgameView.ts, src/views/Home/components/HeaderCard/HeaderCard.tsx, src/views/Home/components/HeaderCard/useHeaderCard.tsx, src/views/Home/components/HomeButton/HomeButton.tsx, src/views/RoadmapMilestones/components/MilestoneCard/MilestoneCard.tsx
https://trello.com/c/YxcCfWCl/562-make-the-back-navigation-accurate
Make the back/forward navigation accurate & improve navigation in general
=> [FIX-562] Make the back navigation accurate

src/components/FancyTabs/FancyTabs.tsx, src/core/utils/dictionary.js, src/views/Contributors/components/ContributorsCategoryCard.stories.tsx, src/views/Contributors/components/ContributorsCategoryCard.tsx, src/views/Contributors/components/TeamCard.tsx
=> Add the subtitle and add the card component

src/components/TeamHeader/CoreUnitSubmissionLink.tsx, src/components/TeamHeader/TeamHeader.tsx, src/views/RecognizedDelegatesBudgetStatement/RecognizedDelegatesBudgetStatementView.stories.tsx, src/views/RecognizedDelegatesBudgetStatement/RecognizedDelegatesBudgetStatementView.tsx, src/views/RecognizedDelegatesBudgetStatement/components/DelegatesActuals/DelegatesActuals.tsx, src/views/RecognizedDelegatesBudgetStatement/components/DelegatesActuals/useDelegatesActuals.ts, src/views/RecognizedDelegatesBudgetStatement/components/DelegatesForecast/DelegatesForecast.tsx, src/views/RecognizedDelegatesBudgetStatement/components/DelegatesForecast/useDelegatesForecast.ts, src/views/RecognizedDelegatesBudgetStatement/useRecognizedDelegatesReport.tsx
RESKIN BSS-1 Budget Statements: Recognized Delegates view
=> [FEAT-459] RESKIN BSS-1 Budget Statements: Recognized Delegates view

src/components/FiltersBundle/useFiltersBundle.ts, src/components/SortsBundle/useSortsBundle.ts
Updating sky-staging with `fix/617-fix-scrolling-behavior-in-mobile-devices`
=> fix: Fix scrolling behavior in mobile devices

src/views/Home/components/GovernanceSection/GovernanceSection.tsx, src/views/Home/components/GovernanceSection/Proposal/Proposal.tsx, src/views/Home/components/GovernanceSection/Proposals/Proposals.tsx
Fixed hydration errors in the console
=> [Fix-614] Fix Governance hydration errors

src/views/Home/components/Contributors/ProfileUpdated.tsx
=> Remove the error in the contributors section

src/views/BudgetStatement/BudgetStatementView.tsx, src/views/BudgetStatement/useBudgetStatementView.ts
https://trello.com/c/3qMKYLNp/494-bss-11-budget-statement-pages-for-keepers
Update the logo for Keepers, SPFs and aligned delegates in their budget statements page
=> [T-494] Update logo for keepers, spfs and aligned delegates

pages/activity-feed/index.tsx, src/stories/components/CUActivityTable/CUActivityItem.tsx, src/stories/components/CUActivityTable/utils/helpers.ts, src/stories/containers/GlobalActivity/useGlobalActivity.ts
https://trello.com/c/fVjosRoD/396-missing-data-in-the-global-activity-feed-view
Now handled special cases and workarounds for some events that are not showing the data
=> [T-396] Fix global activity feed special cases

src/views/Home/components/ButtonLinkAvatar/ButtonLinkAvatar.stories.tsx, src/views/Home/components/ButtonLinkAvatar/ButtonLinkAvatar.tsx
=> Update the button link avatar

src/components/InternalLinkButton/InternalLinkButton.tsx
=> [Feat-610] Add the styles for the card

src/stories/components/CUActivityTable/utils/helpers.ts, src/stories/containers/GlobalActivity/useGlobalActivity.ts
=> Fix missing data in global activity feed

src/views/Contributors/components/ContributorsCategoryCard.stories.tsx, src/views/Contributors/components/Sections/ContributorsCategorySection.tsx, src/views/Contributors/components/Sections/useContributorsCategorySection.tsx
=> [Feat-610] Add the stories and fix border mobile

src/views/Home/components/RoadmapSection/RoadmapSection.tsx
=> Add the border for the tab in road map sections

src/components/MinimalInternalLinkButton/MinimalInternalLinkButton.stories.tsx, src/components/MinimalInternalLinkButton/MinimalInternalLinkButton.tsx
https://trello.com/c/xty3GWcu/555-improve-external-internal-link-components
=> Add new button link minimalist

src/views/Contributors/components/ContributorsCategoryCard.tsx, src/views/Contributors/components/Sections/ContributorsCategorySection.stories.tsx, src/views/Contributors/components/Sections/ContributorsCategorySection.tsx, src/views/Home/components/ButtonLinkAvatar/ButtonLinkAvatar.tsx
=> [Feature-610] Sections categories stories section

src/views/Home/components/FinancesBarChartCard/FinancesBarChartCard.tsx
https://trello.com/c/BRYDUzRN/633-hom-211-dsr-cost-finances-homepage-section
Fix tooltip titles
=> [FIX-633] Fix tooltip titles

src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.stories.tsx, src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx
https://trello.com/c/31nt6vTi/676-incorrectly-positioned-reserves-chart-filter
=> [Fix-676] Incorrectly positioned reserves chart filter

pages/login/index.tsx, src/stories/containers/Auth/Login/LoginContainer.tsx, src/stories/containers/CUActivity/CUActivityFeedContainer.tsx, src/stories/containers/GlobalActivity/GlobalActivityFeedContainer.tsx, src/stories/containers/RecognizedDelegates/RecognizedDelegatesContainer.tsx
https://trello.com/c/sufJlCyH/692-apply-the-new-background-to-the-login-view
[X] Add background for Login
[X] Add background for Activity Feed page
[X] Add background for Global Activity Feed page
[X] Add background for  Recognized Delegates page
=> [Fix-692] Add the correct background for Login page

src/components/AdvancedInnerTable/TransparencyCard/TransparencyCard.tsx, src/components/BudgetStatement/BudgetStatementAuditorComments/ParticipantRoles.tsx, src/components/FiltersBundle/defaults/CumulativeFilter/CumulativeSelectItem.tsx, src/components/TopBarNavigation/MenuUser/MenuItemUser.tsx, src/components/TopBarNavigation/MenuUser/MenuUserOptions.tsx, src/stories/components/CUActivityTable/ActivityTable.tsx, src/stories/components/CuTableColumnLinks/CuTableColumnLinks.tsx, src/stories/components/Header/EssentialWebsites/EssentialWebsites.tsx, src/stories/components/MenuNavigation/MenuTheme/MenuItemTheme.tsx, src/stories/components/MenuNavigation/MenuTheme/MenuTheme.tsx, src/stories/components/Pagination/BreadCrumbWithIcons.tsx, src/stories/components/Pagination/Breadcrumb.tsx, src/stories/containers/Users/UserProfile/UserProfile.tsx, src/views/ActorProjects/components/DeliverableCard/DeliverableCard.tsx, src/views/ActorProjects/components/ProjectCard/ProjectCard.tsx, src/views/BudgetStatement/components/BudgetStatementSummary/BudgetStatementSummary.tsx, src/views/CoreUnitAbout/components/NavigationCard/NavigationCard.tsx, src/views/EcosystemActorAbout/EcosystemActorAboutView.tsx, src/views/Endgame/components/KeyChangeSection/KeyChangeSection.tsx, src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/MobileChart/MobileChart.tsx, src/views/RoadmapMilestones/components/MilestoneDetailsCard/MilestoneProgress.tsx
https://trello.com/c/v9tL35Ao/639-console-errors-are-still-visible-on-different-pages
Fix some console errors & warnings
=> [FIX-639] Fix some console errors & warnings

src/views/Finances/components/SectionPages/BreadcrumbYearNavigation.tsx
https://trello.com/c/MErYellj/698-apply-the-proper-font-to-the-budget-metrics-element
=> [Fix-698]Add the correct font-family

src/components/CookiesPolicyBanner/CookiesPolicyBanner.stories.tsx, src/components/CookiesPolicyBanner/CookiesPolicyBanner.tsx, src/components/SecondaryButton/SecondaryButton.tsx, src/components/SkyButton/SkyButton.tsx, src/core/context/MainWrapper.tsx
https://trello.com/c/V1BdnV9Z/693-cookies-banner-update
Cookies banner update
=> [FIX-693] Cookies banner update

src/views/ActorProjects/components/ProjectCard/ProjectCard.tsx
https://trello.com/c/uL7Ap19i/707-remove-view-ecosystem-actor-button
=> [Fix-707] Remove the link button

src/core/models/interfaces/deliverables.ts, src/views/ActorProjects/components/ProjectCard/ProjectCard.tsx
https://trello.com/c/OCwjPfue/712-inconsistent-key-result-container-height
Inconsistent key result container height
=> [FIX-712] Inconsistent key result container height

src/stories/containers/RecognizedDelegates/components/DelegateExpenseBreakdownCard.tsx, src/stories/containers/RecognizedDelegates/components/MedianAnnualDai.tsx, src/stories/containers/RecognizedDelegates/components/TotalExpenseReportCard.tsx, src/stories/containers/RecognizedDelegates/components/VisualizationCard.tsx, src/views/Endgame/components/BudgetDoughnutChart/BudgetDoughnutChart.tsx, src/views/Endgame/components/TotalBudgetContent/TotalBudgetContent.tsx, src/views/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx, src/views/Finances/components/SectionPages/CardChartOverview/OverviewCardKeyDetailsBudget/DoughnutChartFinances/DaiToolTipIcon.tsx, src/views/Home/utils/utils.tsx
https://trello.com/c/Tk1WgLIi/722-change-dai-to-usd-across-the-site
Change DAI to USD across the site
=> [FIX-722] Change DAI to USD across the site

src/components/CuHeadlineText/CuHeadlineText.tsx, src/components/InternalLinkButton/InternalLinkButton.tsx, src/components/PlaceHolders/BudgetStatementsPlaceholder.tsx, src/views/CoreUnitAbout/components/NavigationCard/CardExpenses.tsx, src/views/CoreUnitsIndex/ListMobileSheetIconArrow.tsx, src/views/CoreUnitsIndex/components/CuRenderLinks/CuRenderLinks.tsx, src/views/EcosystemActorAbout/components/CardProjects/CardProjects.tsx, src/views/EcosystemActorAbout/components/CardProjects/ItemCustomProject.tsx, src/views/Finances/components/CardNavigationFinance/CardNavigationFinance.tsx, src/views/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx, src/views/Home/components/Contributors/ContributorsItem.tsx, src/views/Home/components/FinancesBarChartCard/FinancesBarChartCard.tsx
https://trello.com/c/xty3GWcu/555-improve-external-internal-link-components
=> [Fix-555] Improve external and internal link components

src/views/ActorProjects/components/ProjectCard/ProjectCard.tsx
https://trello.com/c/HU0HtGMs/727-delay-in-loading-the-project-image
Delay in loading the project image
=> [FIX-727] Delay in loading the project image

src/components/CustomSelect/CustomSelect.tsx
https://trello.com/c/RfaLXVNL/724-components-optimizations
=> fix: error on local development in the `CustomSelect` Component

src/components/BudgetStatement/BudgetStatementForecast/BarWithDottedLine.tsx
https://trello.com/c/fQAz9iPe/746-color-misrepresentation-in-ph-september-2024
Fix Color misrepresentation in PH September 2024
=> [FIX-746] Color misrepresentation in PH September 2024

.env.example, src/web3/constants.ts
https://trello.com/c/YW4bwuUz/907-change-the-rpc-endpoint-to-be-an-env-var
Move the RPC URL to an env variable
=> feat: move RPC url to an environment variable

.github/workflows/dev-deploy.yaml, .github/workflows/staging-deploy.yaml
https://trello.com/c/vfuPCBcS
Added `NEXT_PUBLIC_ETH_MAINNET_RPC` env variable to dspot controlled envs: development and staging
=> fix: add missing env var to actions
