powerhouse-inc/fusion

- src/views/Finances/components/BreakdownTableFinances/BreakdownTableFinances.tsx
- src/views/Finances/components/HeaderTable/HeaderAnnually/CellAnnually.tsx
- src/views/Finances/components/HeaderTable/HeaderAnnually/HeaderAnnually.tsx
- src/views/Finances/components/HeaderTable/HeaderMonthly/CellMonthly.tsx
- src/views/Finances/components/HeaderTable/HeaderMonthly/HeaderMonthly.tsx
- src/views/Finances/components/HeaderTable/HeaderQuarterly/CellQuarterly.tsx
- src/views/Finances/components/HeaderTable/HeaderQuarterly/HeaderQuarterly.tsx
- src/views/Finances/components/HeaderTable/HeaderSemiAnnual/CellSemiAnnual.tsx
- src/views/Finances/components/HeaderTable/HeaderSemiAnnual/HeaderSemiAnnual.tsx
- src/views/Finances/components/HeaderTable/HeaderTable.tsx
- src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTable.tsx
Updated the header of the breakdown table with the new styles
> [Reskin-491] Breakdown table header

- src/views/Finances/components/SectionPages/CardChartOverview/OverviewCardKeyDetailsBudget/DoughnutChartFinances/CardLegend.tsx
- src/views/Finances/components/SectionPages/CardChartOverview/OverviewCardKeyDetailsBudget/DoughnutChartFinances/ItemLegendDoughnut.tsx
- src/views/Finances/components/SectionPages/CardChartOverview/useCardChartOverview.tsx
- src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/DesktopChart/DesktopChart.tsx
The legend was overlapping with each other in some specific cases
> [Reskin-485] Fix legend overlap in pie chart

- src/views/Finances/components/SectionPages/CardsNavigation/CardsNavigation.tsx
If there's only one card, then it should be displayed in one column without covering all the container width
> [Reskin-485] Fix single card display issue

- src/components/Breadcrumb/Breadcrumb.tsx
- src/views/Finances/components/SectionPages/BreadcrumbYearNavigation.tsx
The breadcrumb segments where getting an incorrect with on first render, this is now fixed
> [Reskin-485] Fix breadcrumb on first render

- src/stories/components/svg/close.tsx
- src/views/Finances/components/BudgetMetricsModal/BudgetMetricsModal.tsx
Applied the reskin to the budget modal in the finance's page
> [Reskin] Applied reskin to the Metrics modal

- src/views/Finances/components/SectionPages/OverviewSection/BudgetUtilizationCard/BudgetUtilizationCard.tsx
Use the same % logic we use in pie chart legend in the budget utilization percentage
> fix: update utilization percentage number UI

- src/views/Finances/FinancesView.tsx
- src/views/Finances/components/SectionPages/ExpenseMetricsSection/ExpenseMetricsSection.tsx
- src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx
- src/views/Finances/components/WaterfallChart/BarWaterfall.tsx
- src/views/Finances/components/WaterfallChart/LegendAxis.tsx
- src/views/Finances/components/WaterfallChart/LegendItems.tsx
- src/views/Finances/components/WaterfallChart/LegendYitems.tsx
- src/views/Finances/components/WaterfallChart/WaterfallSkeleton.tsx
> [Reskin-490] Add the loading state for reserve chart

- next-env.d.ts
- src/views/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
The filters of the breakdown table weren't allowed to change
> fix: breakdown table filter

- src/views/Finances/components/BreakdownChartSection/BreakdownChart/LegendBreakDownChart/LegendBreakDownChart.tsx
- src/views/Finances/components/ReservesWaterfallFilters/BudgetItem.tsx
>  [Fix-490] Add the placeholder when there is not image provide for the API

- next-env.d.ts
- src/components/FiltersBundle/useFiltersBundle.ts
- src/views/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
Fixed the reset filter button in the breakdown table
> Fix breakdown filter reset option

- pages/_app.tsx
- src/stories/containers/CookiesPolicy/useCookiesPolicyBanner.ts
https://trello.com/c/1s6MFOqA/585-apply-the-dark-mode-as-default-theme
Now the dark theme is the default theme
> [Reskin-585] Apply dark mode theme as default theme

- src/views/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
> Fix the filter in breakdown table

- src/core/hooks/useBudgetStatementPager.ts
https://trello.com/c/j7lqyGlI/463-bss-0-global-requirements-for-bsss
Allow to navigate till the latest budget statement with data instead of a +1 month
> [BSS] Fix navigate till the latest budget statement only

- src/views/Home/components/Contributors/ContributorsItem.tsx
https://trello.com/c/HsoaPE5o/595-fix-all-tab-in-the-contributors-section
> [QA-595] Add the categories in the all tab

- src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx
- src/views/Home/components/Contributors/ContributorsItem.tsx
https://trello.com/c/HsoaPE5o/595-fix-all-tab-in-the-contributors-section
> [QA-595] Fix the space

- next-env.d.ts
- src/components/TopBarNavigation/LinkNavBar.tsx
- src/components/TopBarNavigation/useTopBarNavigation.tsx
https://trello.com/c/Ay6IhyaY/601-add-new-external-icon-to-connet-item
> [Reskin-601] Add connect icon

- src/views/Finances/components/BreakdownChartSection/useBreakdownChart.ts
https://trello.com/c/rRucpp5k/611-fix-the-deeplink-applied-in-breakdown-chart
> [Reskin-611] Fix filters restoration in breakdown chart

- app/robots.ts
- src/components/FiltersBundle/types.ts
- src/core/hooks/useRestorationFromUrlState.ts
- src/views/Finances/components/BreakdownChartSection/useBreakdownChart.ts
- src/views/Finances/components/ExpenseMetrics/useExpenseMetrics.tsx
- src/views/Finances/components/FinancesTable/FinancesTable.tsx
- src/views/Finances/components/SectionPages/BreakdownTable/BreakdownTable.tsx
- src/views/Finances/components/SectionPages/BreakdownTable/useBreakdownTable.tsx
- src/views/Finances/components/SectionPages/ExpenseReports/useExpenseReports.tsx
- src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
- src/views/Finances/types.ts
https://trello.com/c/rRucpp5k/611-fix-the-deeplink-applied-in-breakdown-chart
Allow to conserve the filter state when the URL is shared
> [Reskin-611] Keep and restore filter status in the URL

- src/views/Finances/components/BreakdownChartSection/useBreakdownChart.ts
https://trello.com/c/NiBjQ4cs/615-breakdown-chart-filter-wrong-behavior
Some filters were showing the budget data, this was fixed
> Fix breakdown chart filtering

- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelect/type.ts
- src/components/FiltersBundle/types.ts
- src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/useReservesWaterfallChart.tsx
https://trello.com/c/5deezFMQ/626-fix-avatar-in-roadmaps-section
> [Fix-626] Add the height to the filter

- src/components/Footer/data.tsx
https://trello.com/c/SoK5CWMq/612-footer-linking-updates-sept-13
Update the docs link in the Footer
> [FIX-612] Update the docs link in the Footer

- src/components/CustomSelect/CustomSelect.tsx
- src/views/Finances/components/DelegateExpenseTrend/DelegateExpenseTrendItem.tsx
- src/views/Home/components/FinancesLineChart/FinancesLineChart.tsx
- src/views/Home/components/GovernanceSection/Proposals/Proposals.tsx
https://trello.com/c/5deezFMQ/626-fix-scroll-bar-in-the-reserves-chart-filters
> [Fix-626] Fix the scroll in the reserve chart

- .github/workflows/production-deploy.yaml
https://trello.com/c/sElhmuTd
The legacy production environment auto-deploy in the github actions is now disabled, it need to be deployed manually from any tag or branch
> Disable legacy Production  env auto deploy

- src/views/Contributors/components/ContributorsCategoryCard.tsx
- src/views/Contributors/components/Sections/ContributorsCategorySection.tsx
- src/views/Contributors/components/Sections/ContributorsSections.tsx
- src/views/Contributors/components/Sections/useContributorsCategorySection.tsx
- src/views/Contributors/components/TeamCard.tsx
- src/views/EcosystemActorsIndex/components/ActorItem/ActorItem.stories.tsx
- src/views/Home/HomeView.tsx
- src/views/Home/components/Contributors/ContributorsSection.tsx
> [Feat-610]Add the current team tab

- src/views/Finances/components/SectionPages/ExpenseReports/ExpenseReportsFilters.tsx
https://trello.com/c/lC3i4BF2/638-apply-the-proper-color-to-status-chip-in-budget-statements-filter
> [Fix-638] Add the same component for the filters

- src/views/Finances/useFinancesView.tsx
https://trello.com/c/ugz1Mvkk/635-filters-are-removed-from-the-url-when-the-year-is-changed
When the year is changed it heeps the saved filters in the URL queries
> [Fix-635] Fix year changes reset query parameters in URL

- src/views/Contributors/components/Sections/ContributorsCategorySection.tsx
- src/views/Contributors/components/Sections/ContributorsSections.tsx
- src/views/Home/components/Contributors/useContributorsSection.tsx
> [Feat-610] Fix the homeview contributors item

- src/components/TeamHeader/CoreUnitSubmissionLink.tsx
- src/views/RecognizedDelegatesBudgetStatement/components/DelegatesActuals/DelegatesActuals.tsx
- src/views/RecognizedDelegatesBudgetStatement/components/DelegatesActuals/useDelegatesActuals.ts
- src/views/RecognizedDelegatesBudgetStatement/components/DelegatesForecast/DelegatesForecast.tsx
- src/views/RecognizedDelegatesBudgetStatement/components/DelegatesForecast/useDelegatesForecast.ts
- src/views/RecognizedDelegatesBudgetStatement/components/TransactionLink/TransactionLink.tsx
https://trello.com/c/o6iaVCPd/459-bss-1-budget-statements-recognized-delegates-view
RESKIN BSS-1 Budget Statements: Recognized Delegates view (Forecast Tab)
> [FEAT-459] RESKIN BSS-1 Budget Statements: Recognized Delegates view (Forecast Tab)

- src/views/Contributors/components/ContributorsCategoryCard.tsx
- src/views/Contributors/components/Sections/ContributorsCategorySection.tsx
- src/views/Contributors/components/TeamCard.tsx
- src/views/Home/components/ButtonLinkAvatar/ButtonLinkAvatar.tsx
> [Feat-610] Add styles subcard teams in contributors

- src/views/Contributors/components/ContributorsCategoryCard.tsx
- src/views/Home/components/ButtonLinkAvatar/ButtonLinkAvatar.tsx
> Fix the colors arrow in the ButtonLinkAvatar

- src/views/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
https://trello.com/c/Mkt3vKmL/675-missing-x-y-axis-in-the-breakdown-chart
> Fix the breakdown chart dont show legend

- src/views/Home/components/FinancesBarChartCard/FinancesBarChartCard.tsx
https://trello.com/c/lzXiqnzT/674-buttons-positioned-too-close-together-in-the-finances-section
Buttons Positioned Too Close Together in the Finances section
> [FIX-674] Buttons Positioned Too Close Together in the Finances section

- src/views/Home/components/FinancesBarChart/FinancesBarChart.tsx
- src/views/Home/components/FinancesLineChart/FinancesLineChart.tsx
https://trello.com/c/hSbvei2m/673-expense-breakdown-chart-appears-cut-off
Expense breakdown chart appears cut off
> [FIX-673] Expense breakdown chart appears cut off

- src/views/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
https://trello.com/c/Mkt3vKmL/675-missing-x-y-axis-in-the-breakdown-chart
> [Fix-675] Add the line in the quarterly metrics

- src/views/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
https://trello.com/c/Mkt3vKmL/675-missing-x-y-axis-in-the-breakdown-chart
> Fix line in table

- pages/500.tsx
- pages/_app.tsx
- src/components/Error/CustomError.tsx
- src/components/Error/ErrorBoundary.tsx
- src/core/utils/dictionary.js
- src/views/Page404/Page404View.tsx
- src/views/Page500/Page500View.stories.tsx
- src/views/Page500/Page500View.tsx
https://trello.com/c/YEcu2osm/681-create-a-load-error-page
Create a load error page
> [FEAT-681] Create a load error page

- src/views/Finances/FinancesView.tsx
https://trello.com/c/M2ZP9tfv/690-makerdao-text-should-be-changed-to-sky
MakerDao text should be changed to Sky
> [FIX-690] MakerDao text should be changed to Sky

- src/views/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/views/Finances/components/ExpenseMetrics/ExpenseMetricsChart/ExpenseMetricsChart.tsx
- src/views/Finances/components/LineYearBorderBottomChart/LineYearBorderBottomChart.tsx
- src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx
https://trello.com/c/dSvkBxBU/691-chart-legends-show-incorrect-style
> [Fix-691] Add the same style for year line component

- src/views/ActorProjects/api/query.ts
- src/views/ActorProjects/components/DeliverableCard/DeliverableCard.tsx
- src/views/ActorProjects/components/ProjectCard/ProjectCard.tsx
https://trello.com/c/A7HtpHeT/696-api-breaking-change
> [Fix-696] Fix the query with new breaking change

- src/views/Finances/components/ExpenseMetrics/ExpenseMetricsFinances.tsx
- src/views/Finances/components/SectionPages/OverviewSection/UtilizationChart/DesktopChart/DesktopChart.tsx
https://trello.com/c/yVTzl6Gi/695-pie-chart-legend-is-displayed-outside-of-the-section
Fix: pie chart legend is displayed outside of the section
> [FIX-695] Pie chart legend is displayed outside of the section

- src/components/CustomSelect/CustomSelect.tsx
https://trello.com/c/UPrYABHE/697-fix-filter-behavior-in-the-reserves-chart
Fix filter behavior in the Reserves Chart
> [FIX-697] Fix filter behavior in the Reserves Chart

- src/views/Finances/components/WaterfallChart/WaterfallChart.tsx
https://trello.com/c/1v3nrPls/694-values-overlap-with-legend-items-in-reserve-chart
> [Fix-694] Reduce the space when there its negative number

- src/views/Finances/FinancesView.tsx
- src/views/Finances/components/ExpenseMetrics/ExpenseMetricsFinances.tsx
https://trello.com/c/uFascx9g/689-metrics-line-char-doesnt-show-the-levels-name
-[X] The title should show the level name followed by "Expense Metrics."
> Add the text to title of level in finances page in line chart section

- src/views/ActorProjects/components/DeliverableStatusChip/DeliverableStatusChip.tsx
https://trello.com/c/1wgvshMr/708-orange-color-no-applied-to-the-todo-chip
[X] Add the new blocked status
[X] Add the styles for this new blocked status
> [Fix-708] Add the new blocked status

- src/views/Finances/components/LineYearBorderBottomChart/LineYearBorderBottomChart.tsx
https://trello.com/c/1v3nrPls/694-values-overlap-with-legend-items-in-reserve-chart
> Add correct space between the line and legend in waterfall

- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelect/type.ts
- src/components/CustomSelect/useCustomSelect.ts
- src/components/FiltersBundle/FilterDesktop.tsx
- src/components/FiltersBundle/FiltersList.tsx
- src/components/FiltersBundle/defaults/CumulativeFilter/CumulativeFilter.tsx
- src/components/SortsBundle/SortTablet.tsx
- src/components/SortsBundle/SortsList.tsx
- src/components/TopBarNavigation/TopBarNavigation.tsx
- src/views/Finances/components/SectionPages/BreadcrumbYearNavigation.tsx
- styles/globals.scss
https://trello.com/c/QijnXnF6/699-dropdown-remains-visible-while-scrolling-through-the-view
Dropdown remains visible while scrolling through the view
> [FIX-699] Dropdown remains visible while scrolling through the view

- src/views/Endgame/components/BudgetTransitionChart/BudgetTransitionChart.tsx
https://trello.com/c/i6ugkU9g/704-bars-are-shown-with-no-space-between-them
Bars are shown with no space between them
> [FIX-704] Bars are shown with no space between them

- src/views/Finances/components/ExpenseMetrics/ExpenseMetricsFinances.tsx
- src/views/Finances/components/SectionPages/ReservesWaterfallChartSection/ReservesWaterfallChartSection.tsx
https://trello.com/c/7yDWN3l7/711-filters-aligned-to-the-left-side
Fix filters aligned to the left side
> [FIX-711] Filters aligned to the left side

- src/views/ActorProjects/ActorProjectsView.tsx
https://trello.com/c/hkPr1d1a/730-header-is-shown-behind-the-breadcrumb
> [Fix-730] Add the correct space header and breadcrumb navigation

- src/components/AdvancedInnerTable/AdvancedInnerTable.tsx
https://trello.com/c/XGSJzbpR/728-wrong-color-in-budget-statements
> [Fix-728] Fix the color in budget group

- src/components/CustomSelect/CustomSelect.tsx
- src/components/CustomSelect/useCustomSelect.ts
- src/views/Finances/components/SectionPages/BreadcrumbYearNavigation.tsx
https://trello.com/c/cZpFA2XB/726-wrong-behavior-in-the-filters
Wrong behavior in the filters
> [FIX-726] Wrong behavior in the filters

- src/components/Container/Container.tsx
- src/views/Endgame/components/BudgetTransitionChart/BudgetTransitionChart.tsx
- src/views/Finances/components/BreakdownChartSection/BreakdownChart/BreakdownChart.tsx
- src/views/Finances/components/ExpenseMetrics/ExpenseMetricsChart/ExpenseMetricsChart.tsx
- src/views/Home/components/FinancesBarChart/FinancesBarChart.tsx
- src/views/Home/components/FinancesLineChart/FinancesLineChart.tsx
- src/views/Home/components/FinancesLineChartCard/FinancesLineChartCard.tsx
https://trello.com/c/QKH5ZW0S/733-horizontal-scroll-appears-when-hovering-over-the-breakdown-chart
Horizontal scroll appears when hovering over the Breakdown chart
> [FIX-733] Horizontal scroll appears when hovering over the Breakdown chart

- src/components/Card/Card.stories.tsx
https://trello.com/c/h6dNbqjF/737-identify-fusion-components-without-story-storybooks
> [Stories-737] Add the storie for card component

- src/components/BudgetStatement/BudgetStatementForecast/BarWithDottedLine.tsx
https://trello.com/c/fQAz9iPe/746-color-misrepresentation-in-ph-september-2024
Color misrepresentation in PH September 2024
> [FIX-746] Color misrepresentation in PH September 2024

- src/views/Endgame/components/KeyChangesBudgetTransitionStatusImportantLink/KeyChangesBudgetTransitionStatusImportantLink.tsx
- src/views/Endgame/components/KeyChangesSections/Sections/GovernanceSection.tsx
https://trello.com/c/nvQM7CwD/906-outdated-content-and-broken-links-on-endgame-budget-structure-page
- Should fix the https://fusion.sky.money/delegates link
- Should forum.makerdao.com directs to forum.sky.money
> fix: outdated content and broken links in endgame
